/**
 * Vertical typesetting metrics + punctuation optical centering for Figma.
 *
 * 行距 (column pitch) = cp, NOT glyph width cw.
 * 標點置中: CENTER_PUNCT glyphs are placed in a punct overlay layer,
 * optically nudged; the body column uses ideographic space 　 in those slots.
 */
module.exports = {
  rows: 32,
  cols: 15,
  cw: 13.125,
  cp: 21.55,
  lh: 14.7,
  fs: 10.5,
  bindingMm: 18,
  outerMm: 15,
  trimMm: { w: 152, h: 230 },
  centerPunct: ["，", "。", "、", "：", "；", "！", "？", "︐", "︒", "︑", "︓", "︔", "︕", "︖"],
  punctOptical: {
    "︐": [-0.26, 0.28],
    "︒": [-0.26, 0.28],
    "︑": [-0.26, 0.28],
    "︓": [-0.22, 0.18],
    "︔": [-0.22, 0.22],
    "︕": [-0.18, 0.12],
    "︖": [-0.18, 0.12],
  },
  verticalForms: {
    "，": "︐",
    "、": "︑",
    "。": "︒",
    "：": "︓",
    "；": "︔",
    "！": "︕",
    "？": "︖",
    "「": "﹁",
    "」": "﹂",
    "『": "﹃",
    "』": "﹄",
    "（": "︵",
    "）": "︶",
    "【": "︻",
    "】": "︼",
    "《": "︽",
    "》": "︾",
    "〈": "︿",
    "〉": "﹀",
    "〔": "︹",
    "〕": "︺",
    "［": "﹇",
    "］": "﹈",
    "—": "︱",
    "─": "︱",
    "－": "︱",
    "–": "︱",
    "…": "︙",
    "·": "・",
  },
};
